### ISSUE TITLE
UI bug with Create Alert Integration

### ISSUE THREAD

**Issue by truedays** [pingsphere-io/pingsphere.io#4]
There's a User-Interface bug after creating an Alert Integration at https://pingsphere.io/alert/integration.

Steps to reproduce:

1. Go to https://pingsphere.io/alert/integration#
2. Click Create Alert Integration
3. Create a PagerDuty integration and fill in any required fields and click ADD
4. Click Create Alert Integration again

Results: Pagerduty integration selector is highlighted, but only email integration options exists.
Expected: Integration selector should match configuration options

Screenshot shows PAGERDUTY selected, but only email configuration options exists:
![image](https://user-images.githubusercontent.com/1525206/69958795-2a5ee480-14cb-11ea-9f59-94679f67999c.png)

**Comment by austin-barrington** [comment]
Thank you @truedays I've found the issue and fixed it in a development environment. I'll put this in the next release.

**Comment by austin-barrington** [comment]
This was fixed in a recent release thank you very much!
